name: Github Release

on:
  create:
    tags:
      - permute-mmo-filter-*

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name:
      run: for f in target/*-jar-with-dependencies.jar; do mv "$f" "$(echo "$f" | sed -E 's/(.*\/).*-([0-9.]+)-.*/\1PermuteMMOFilter-\2.jar/')"; done
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          target/PermuteMMOFilter-*.jar
