name: Maven Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type to cange which version numbers to bump."
        required: true
        type: choice
        options:
        - incremental
        - minor
        - major

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.BUILD_AUTOMATION_PAT}}
        persist-credentials: true
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: maven

    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Maven Release
      run: | 
        case "${{github.event.inputs.releaseType}}" in
        major)
          mvn build-helper:parse-version release:prepare release:perform -B -s .maven_settings.xml -DreleaseVersion='${parsedVersion.nextMajorVersion}.0.1' -DdevelopmentVersion='${parsedVersion.nextMajorVersion}.0.2-SNAPSHOT'
          ;;
        minor)
          mvn build-helper:parse-version release:prepare release:perform -B -s .maven_settings.xml -DreleaseVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.1' -DdevelopmentVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.2-SNAPSHOT'
          ;;
        incremental|*)
          mvn build-helper:parse-version release:prepare release:perform -B -s .maven_settings.xml -DreleaseVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}' -DdevelopmentVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT'
          ;;
        esac
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_AUTOMATION_PAT }}
